### ISSUE TITLE
Need to fix -Warning message is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#1]
When I have activate the DIVI theme then below error message is display.

![image](https://user-images.githubusercontent.com/75515088/116970180-22652e80-acd5-11eb-9456-1646f6862741.png)

**Comment by mistry-jignesh** [comment]
Again I have verified issue . This issue is reproduced.

![image](https://user-images.githubusercontent.com/75515088/118442837-c1901a00-b708-11eb-8f3d-3bbee3ac5601.png)

**Comment by pooja-pragda** [comment]
The issue is the same as #10 Need to fix - Create a DIVI page issue. Commented there.

**Comment by mistry-jignesh** [comment]
As per @Pooja-pragda madam comment ,The error is from the Divi theme not from our addon. Is because of the need to update Divi as woo-commerce updated.

So now I have closed the issue.
