### ISSUE TITLE
Need to fix - Create a DIVI page issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#10]
Try to create a page using DIVI option then it is display below error message.

![image](https://user-images.githubusercontent.com/75515088/118460374-446da080-b71a-11eb-80ee-17dea3145e40.png)

**Comment by pooja-pragda** [comment]
The error is from the Divi theme not from our addon. Is because of the need to update Divi as woo-commerce updated.

**Comment by mistry-jignesh** [comment]
As per @pooja-pragda madam comment ,The error is from the Divi theme not from our addon. Is because of the need to update Divi as woo-commerce updated.

So now I have closed the issue.
