### ISSUE TITLE
Need to fix -Divi theme- Past event listing - Spacing issue in event box view/list view

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#14]
Divi theme- Past event listing -

 Spacing issue in event box view/list view . 

please check screenshot.

![image](https://user-images.githubusercontent.com/75515088/120184919-2a11e780-c22f-11eb-9c99-3c608a3ec582.png)
![image](https://user-images.githubusercontent.com/75515088/120187106-000df480-c232-11eb-9d9f-8fd3486a3baf.png)

**Comment by pooja-pragda** [comment]
can't reproduce this bug.

**Comment by mistry-jignesh** [comment]
Right now this issue is unable to reproduced. 

So I have closed issue.
