### ISSUE TITLE
[ Event filter ] Events listing element show filter

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wpem-divi-elements#18]
when I Used to show filters off in event listing but it shows filters

and please include an option to rewrite upcoming events listing title (Events)

**Comment by live-aamir** [comment]
@mistry-jignesh The filter issue is working fine and upcoming events module is already there. Below is screenshot.
![Screenshot_1](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/f908b6ed-b815-400b-a373-98d050d287b4)

**Comment by mistry-jignesh** [comment]
As per @live-aamir: The filter issue is working fine and the upcoming events module is already there. Below is a screenshot.
So I closed the issue.
