### ISSUE TITLE
Need to fix - When Activate  Divi theme then event listing page loader is display infinite time

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#2]
When Activate  Divi theme then event listing page loader is display infinite time .

![image](https://user-images.githubusercontent.com/75515088/116971393-1d08e380-acd7-11eb-8e19-bc0a07098a74.png)

**Comment by mistry-jignesh** [comment]
Again I have verified issue. This issue is available . 

 Event listing page loader is display infinite time .

**Comment by pooja-pragda** [comment]
The issue is the same as #10 Need to fix - Create a DIVI page issue. Commented there.

**Comment by mistry-jignesh** [comment]
Event listing page loader is display infinite time .
