### ISSUE TITLE
Need to set proper plugin description. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-divi-elements#20]
Need to set proper plugin description in details. 

![image](https://user-images.githubusercontent.com/35419531/127875886-6d9aac81-30c7-4551-b4b8-182c8e03b4d8.png)

**Comment by yukta05** [comment]
Description texts are suggested by @Priya-Goenka . So according to @tamanna-ahuja and @Priya-Goenka plugin description is perfect. so i  close this issue.
