### ISSUE TITLE
Need to fix notice and warning.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-divi-elements#21]
Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\EventDashboard\EventDashboard.php on line 34

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\EventListing\EventListing.php on line 236

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\EventOrganizers\EventOrganizers.php on line 75

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\EventSummary\EventSummary.php on line 87

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\EventVenues\EventVenues.php on line 75

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\OrganizerDashboard\OrganizerDashboard.php on line 34

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\PastEventListing\PastEventListing.php on line 175

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\SingleEvent\SingleEvent.php on line 52

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\SingleOrganizer\SingleOrganizer.php on line 49

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\SingleVenue\SingleVenue.php on line 49

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\SubmitEventForm\SubmitEventForm.php on line 22

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\SubmitOrganizerForm\SubmitOrganizerForm.php on line 22

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\SubmitVenueForm\SubmitVenueForm.php on line 22

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\UpcomingEventListing\UpcomingEventListing.php on line 121

Deprecated: Required parameter $render_slug follows optional parameter $content in D:\xampp\htdocs\wpem\wp-content\plugins\wpem-divi-elements\includes\modules\VenueDashboard\VenueDashboard.php on line 34

![image](https://user-images.githubusercontent.com/35419531/127876206-4b4abe3a-fd48-463a-a9fd-bf874a280bc0.png)

**Comment by kinjal6810** [comment]
already covered issue.

**Comment by yukta05** [comment]
I checked this issue, not facing this issue right now. so I am going to close this issue.
