### ISSUE TITLE
Event per page is not working in event dashboard.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-divi-elements#24]
Event per page is not working in the event dashboard.

I have set only 5 events for listing.

![image](https://user-images.githubusercontent.com/35419531/128147774-d4278cf6-fdb2-4354-9a6d-01e590d6f92f.png)

I can see all events. 

![image](https://user-images.githubusercontent.com/35419531/128147836-8519f2af-5c75-4199-b75d-18f9adf238aa.png)

**Comment by yukta05** [comment]
Issue is duplicated. so i close this issue.
