### ISSUE TITLE
Need to fix event listing issue.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-divi-elements#25]
Event listing is not working after activation Divi elements. I can see a continuously loading after activating Divi elements.

**I am not able to check the Event listing module because of this bug.** 

![image](https://user-images.githubusercontent.com/35419531/128148619-47d89bc2-0462-4803-8609-16faefeb3da6.png)

Added Event listing element but it is not working and loading icon is display.

![image](https://user-images.githubusercontent.com/75515088/169784239-58bb45d4-2299-441a-8fac-7581281aa1d5.png)

![image](https://user-images.githubusercontent.com/75515088/169784533-5ed81bed-3040-4599-8237-b1d89d68197b.png)

**Comment by vijayrathod245** [comment]
It's working fine from my side

**Comment by mistry-jignesh** [comment]
I have verified this issue. 

Event listing element is working fine and loading issue is fixed.

So I closed the issue.
