### ISSUE TITLE
Single event listing attribute not working. 

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wpem-divi-elements#27]
The single event listing attributes not working. 

I can see a blank screen after putting the Single event listing attribute.

![image](https://user-images.githubusercontent.com/35419531/128492928-4c4b7136-7f73-4bd7-ada2-f6c029e8a487.png)

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/171393288-6f872df9-2927-45ea-9518-97b7473fcbde.png)
![image](https://user-images.githubusercontent.com/104058202/171393377-9e5b3839-221e-4276-b438-dcab8bacc2a2.png)
Single event listing attribute is working now

**Comment by yukta05** [comment]
This issue is not reproducible, so i am going to close this issue.
