### ISSUE TITLE
Organizer dashboard - Display error message

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#31]
Display the error message.

![image](https://user-images.githubusercontent.com/75515088/146724404-b8559ed3-4649-4325-9b65-a14279c41f5b.png)

**Comment by kinjal6810** [comment]
already covered 1.0.0 branch

**Comment by vijayrathod245** [comment]
I have checked this issue but it working properly from my side

**Comment by mistry-jignesh** [comment]
Verified this issue.  When I put organizer dashboard in the Divi then error message is display.

![image](https://user-images.githubusercontent.com/75515088/173747431-6f1d36fe-ca40-447a-b02b-d94b5628821a.png)

**Comment by yukta05** [comment]
![image](https://user-images.githubusercontent.com/86232676/175511365-9e0aee31-681d-48f9-8b06-18b14bec15dd.png)
The issue is fixed. so i close this issue.
