### ISSUE TITLE
Past Event listing - Events box/List view icon is not display center 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#32]
Past Event listing - Events box/List view icon is not display center align.
 
![image](https://user-images.githubusercontent.com/75515088/146737818-9ed0f931-444b-46d4-9cd1-1039c5430de3.png)

**Comment by yukta05** [comment]
![image](https://user-images.githubusercontent.com/86232676/172311411-1bdc7991-d74f-40b3-8a54-e7258228c68c.png)

This issue is properly working, so i close this issue.
