### ISSUE TITLE
Past Event Listing - Events list view issue 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#33]
When click on the event list view icon .

Here Event view are not display properly.

![image](https://user-images.githubusercontent.com/75515088/146738710-267c0c9e-f6a6-4857-b675-89bec9f84dac.png)

**Comment by kinjal6810** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/104058202/171386790-1bedcb20-7ddc-491a-aa4c-b95ba1c80d5b.jpg)
Here Event view are display properly now.

**Comment by yukta05** [comment]
![image](https://user-images.githubusercontent.com/86232676/172311411-1bdc7991-d74f-40b3-8a54-e7258228c68c.png)

This issue is properly working, so i close this issue.
