### ISSUE TITLE
Single Event Summary - Event is display outside of the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#36]
When Peform the below setting then  Event is display outside of the page.

**Align set as ="left** .

 It is working fine with  Aligin ="Right ".

![image](https://user-images.githubusercontent.com/75515088/146756356-30b4cdc4-0e6e-46e5-b994-b23bbdbdd4df.png)
![image](https://user-images.githubusercontent.com/75515088/146755992-baa3e3ca-95c3-4ec4-9f45-0656746e7a2c.png)

**Comment by kinjal6810** [comment]
Is According to page center

**Comment by yukta05** [comment]
Not facing any issues right now. so i am going to close this issue

https://user-images.githubusercontent.com/86232676/172302806-bc8bdbdf-231e-4cd7-9f97-c26702966dea.mp4

.
