### ISSUE TITLE
Single Event Summary - Event is not display center 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#37]
When Peform below setting  then event is not display center .

Here Align set as =**Center**.

![image](https://user-images.githubusercontent.com/75515088/146757489-fbf53e05-0cf9-4bb3-8bbb-9b746a3ce827.png)

![image](https://user-images.githubusercontent.com/75515088/146757693-92e37f2f-3481-4703-9658-40f865b32fcb.png)

**Comment by yukta05** [comment]
T

Uploading Untitled_ Jun 07,2022 10_52 AM.mp4…

his issue is working properly, so i am going to close this issue
