### ISSUE TITLE
Submit organizer form - Display fatal error message

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#38]
I have performed below setting. Now fill the details for the organizer .

Click on the submit button. Here display the below the error messag.

Display fatal error message.

![image](https://user-images.githubusercontent.com/75515088/146765395-d4011ebf-9a8c-4a69-848e-692efd734e6e.png)

![image](https://user-images.githubusercontent.com/75515088/146765213-ba9bf3fa-b824-4fdb-b410-e32bfd497466.png)

Also in the backend new organizer entry is availabel.

**Comment by kinjal6810** [comment]
issue is not available now

**Comment by yukta05** [comment]
This issue is not reproducible, so I am going to close this issue
