### ISSUE TITLE
Need to fix - Search text box is having text after refresh the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#4]
Search text box is having text after refresh the page .

![image](https://user-images.githubusercontent.com/75515088/116977334-f0a59500-acdf-11eb-9df5-1c531584c812.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is reproduced .

Search text box is having text after refresh the page .

**Comment by pooja-pragda** [comment]
The issue is again not from our addon.

1. First we don't provide any kind of search widget. 
2. is Default WordPress search widget.
3. may b is customized by the theme developer.

**Comment by mistry-jignesh** [comment]
As per @pooja-pragda  madam comment .The issue is again not from our addon.

So I have closed the issue.
