### ISSUE TITLE
Upcoming event listing - ASC and DESC order is not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#40]
I have peformed below setting .Here events are not display in the order.

![image](https://user-images.githubusercontent.com/75515088/146874375-27c5599e-6e9a-42c8-86c1-fb0579575ffe.png)

Also order by setting is not working.

**Comment by yukta05** [comment]
This issue is not reproducible right now, so i am going to close this issue.
