### ISSUE TITLE
Activate divi theme then code is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#43]
Activate divi theme then code is display on the page.

![image](https://user-images.githubusercontent.com/75515088/166444053-ed253a9c-e9b0-4b4a-aac3-412c3ac0118e.png)

[wpem_single_event _builder_version=”4.9.4″ _module_preset=”default” hover_enabled=”0″ sticky_enabled=”0″][/wpem_single_event]

**Comment by yukta05** [comment]
This issue has been resolved in core plugin. That's why this issue is not reproducible. so i am going to close the issue.
