### ISSUE TITLE
Divi elementor is not working from the backend side.

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wpem-divi-elements#44]
https://user-images.githubusercontent.com/86232676/171859676-cea98434-001d-486a-bc4a-6a8424cdeeba.mp4

Divi elementor is not working from the backend side.
If we activate the classic editor i am able to use Divi element from the backend side.
Facing issue when user not using classic editor plugin,

**Comment by mistry-jignesh** [comment]
As per @vijayrathod245 - This type functionality in divi theme, It means divi theme provide classic editor Enabled or Disabled options.

Now I am use divi elemet at backend side.

So closed the issue.
