### ISSUE TITLE
Two profile banners are showing in organizer. 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wpem-divi-elements#45]
![image](https://user-images.githubusercontent.com/86232676/172550511-d6365d86-e30c-43d5-b4c6-79530706d20f.png)
![image](https://user-images.githubusercontent.com/86232676/172550600-1a60e9e1-8ea2-4c7e-b9a4-7acaa396f6cb.png)

This issue occurs with old data. you can reproduce this issue in your old data. you can also check in staging,
https://staging-appwpeventmanager.kinsta.cloud/organizer-dashboard/

steps for reproducing the issue,
open organizer dashboard 
select any organizer, which you created from the backend. 

https://user-images.githubusercontent.com/86232676/172554736-360a0a18-a84f-46d2-b034-612f457ce5a9.mp4

**Comment by mistry-jignesh** [comment]
Verifie this issue .Now this issue is fixed and working.

Now single banner is display in the organizer.

So I closed the issue.
