### ISSUE TITLE
Backend - Event dashboard - Event per page option is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#47]
Go to Backend > Created new page > Click on the Divi Bulider option.

Now select option as  Event dashboard > Per page added values as 3.

Save the page and click on the view page option.

Here per page not display 3 recored.

![image](https://user-images.githubusercontent.com/75515088/173754601-a0a9dd0c-a409-49fc-bb6b-b249378e1815.png)

![image](https://user-images.githubusercontent.com/75515088/173755098-54ea00e0-62f6-4503-aa44-4fa4a8696262.png)

**Comment by yukta05** [comment]
Here I am not getting the event dashboard page. showing event listing page. need to correct this.

**Comment by yukta05** [comment]
This issue is fixed, so i close this issue.
