### ISSUE TITLE
Backend - Past events listing - Pagination is not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#49]
Past events listing - Pagination is not working .

![image](https://user-images.githubusercontent.com/75515088/173765280-1ab497b5-31fa-4fde-a8a5-bd6d7e4ec5bf.png)

![image](https://user-images.githubusercontent.com/75515088/173765754-27bac295-293b-4e02-ab23-20d1871fa81d.png)

**Comment by yukta05** [comment]
This issue is fixed. so i close this issue.
