### ISSUE TITLE
Backend - Submit event form - In the event details page 2 banner is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#51]
Peformed  below setting at backend.

![image](https://user-images.githubusercontent.com/75515088/174230602-51c41922-94fe-44ca-bc04-18281cf2bf97.png)

Click on the view page . Here post an event page is availabel.

Fill up all details & submit event.

Event is created .  In the event details page 2 banner is display.

![image](https://user-images.githubusercontent.com/75515088/174231422-975df404-ff9d-4eb9-815e-b258126ab09d.png)

**Comment by yukta05** [comment]
Created submit event page from the backend using Divi elementor. and submit event through that created page. 
View that event,all details with a single banner are properly displayed. 

So i close this issue.
