### ISSUE TITLE
Calendar design affected due to Divi elementor 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wpem-divi-elements#52]
![image](https://user-images.githubusercontent.com/86232676/175465812-77154495-0672-46e7-9b58-db22df668004.png)
Here calendar design does not look perfect. Need to fix it.,

**Comment by kprav33n97** [comment]
The issue has been fixed. 

![screencapture-localhost-zoom-events-2-2022-06-27-11_12_36](https://user-images.githubusercontent.com/45144459/175869577-61cd245b-07bc-43be-9e0f-96283767ace2.png)

**Comment by yukta05** [comment]
The issue is fixed, so i close this issue.

**Comment by mistry-jignesh** [comment]
![image](https://user-images.githubusercontent.com/75515088/180420716-a635835b-3e46-4986-8613-e98910827878.png)

Verified this issue. This isssue is represent .

The calendar design issue face with Divi elements.

**Comment by kprav33n97** [comment]
@mistry-jignesh Please check with the latest version of Divi Theme and plugins. You have reopened the issue without checking with the latest version of Divi theme. The bug does not exist with the latest version of divi theme & plugins! 

![screencapture-localhost-latest-events-2022-07-25-12_16_35](https://user-images.githubusercontent.com/45144459/180715527-13554a81-8c29-44e0-88b4-74b65cb98b8a.png)

**Comment by mistry-jignesh** [comment]
Verified  this issue with latest  Divi theme.

Now calendar design  issue is working fine . So I closed the issue.
![image](https://user-images.githubusercontent.com/75515088/180750778-84b00678-0617-43b2-aa8e-2367dfba7071.png)
