### ISSUE TITLE
Map is not showing with event listing option

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#53]
Map is not showing with event listing option .

![image](https://user-images.githubusercontent.com/75515088/178423210-98cb662b-4c47-4031-b764-36e3e6059891.png)

**Comment by live-aamir** [comment]
@mistry-jignesh this is working fine, Below is the screenshot.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/cfe9290e-7318-45f7-b9b0-d1e6112e2aa9)

**Comment by mistry-jignesh** [comment]
I have verified this issue . Now this issue is working fine.
Map is display on the event listing page.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/ef155414-54cc-42b6-893d-938176d24325)
So I closed the issue.
