### ISSUE TITLE
Past event listing - Display error message on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#56]
Past event listing - Display error message on the page.

![image](https://user-images.githubusercontent.com/75515088/180416100-3a2a7e52-9728-406b-820f-9ea21566413d.png)

**Comment by live-aamir** [comment]
@mistry-jignesh No such issue is found. Please check below screenshot.
![Screenshot 2023-11-09 194313](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/1a1d646d-48cb-406c-a9c0-f0fa19cb089c)

**Comment by mistry-jignesh** [comment]
I have verified this issue with the past event listings option.
Still error message is displayed on the page.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/24ac1cea-5bf1-4e38-86c9-37bf0b5f5a84)

**Comment by live-aamir** [comment]
@mistry-jignesh @krinaydhanani This is backend related issue related with react.

**Comment by RavindraSingh2001** [comment]
@mistry-jignesh This is covered in this issue https://github.com/wpeventmanager/wpem-divi-elements/issues/74

**Comment by mistry-jignesh** [comment]
This issue is fixed on the past event listing page.
So I closed the issue.
