### ISSUE TITLE
Event listing - Show filter selected no option then filter is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#57]
Show filter selected no option then filter is display.

![image](https://user-images.githubusercontent.com/75515088/180426954-c24f5704-dcf1-4cb5-b0d2-50da13020703.png)

![image](https://user-images.githubusercontent.com/75515088/180426856-96380872-773a-43bb-a7c2-0e22e65c5167.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is covered in https://github.com/wpeventmanager/wpem-divi-elements/issues/79

**Comment by mistry-jignesh** [comment]
I have verified this issue. Show filter selected as **No option** then the filter is not displayed.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/43421e0f-4706-40a8-baa8-a7d46b49f2c1)

This issue is working fine. So I closed the issue.
