### ISSUE TITLE
Event listing - Select list view option then view page box is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#58]
Event listing - Select list view option then view page box is display

![image](https://user-images.githubusercontent.com/75515088/180428790-eaa39a7c-1eb4-4a61-be75-387dc82a5baa.png)

Event listing - Other attribute is not working fine.

Show Pagination -Option**

**Comment by live-aamir** [comment]
@mistry-jignesh This is working fine. Please ckeck.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is working fine.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/f8b3c678-9ee1-4bc7-b08e-f5766bad8084)

other attribute is not working fine. So I closed the issue.
