### ISSUE TITLE
Submit event form - In the event details page 2 banner is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#60]
Submit event form -

Created new event from the front end using Divi elements.

In the event details page 2 banner is display.

![image](https://user-images.githubusercontent.com/75515088/180444598-ca18b400-faac-4cc5-8cd4-0b615fd26729.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is covered in https://github.com/wpeventmanager/wpem-divi-elements/issues/68

**Comment by mistry-jignesh** [comment]
I have verified this issue. I have performed the mentioned steps in the above issue.
Now click on the any event details page then a single banner is displayed on the page.
Now this issue is working fine. So I closed the issue.
