### ISSUE TITLE
Backend - Submit event form - In the event details page 2 banner is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#67]
Peformed below setting at backend.

![image](https://user-images.githubusercontent.com/75515088/186382678-e7b12d4d-187d-4352-a0e5-3514351b73a9.png)

Click on the view page . Here post an event page is availabel.

Fill up all details & submit event.

Event is created . In the event details page 2 banner is display.

![image](https://user-images.githubusercontent.com/75515088/186382784-3dc0516f-1f3a-439c-acb4-6bcd1d6911d0.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is covered in https://github.com/wpeventmanager/wpem-divi-elements/issues/68

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this is fixed.
It is working fine. Event details page only a single image is displayed.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/07eb3a28-7ca4-470b-9199-10a0fc381784)

So I closed the issue.
