### ISSUE TITLE
Need to fix -My account - Order page issue

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#7]
View text icon larger display than other text.

![image](https://user-images.githubusercontent.com/75515088/116996414-fb205880-acf8-11eb-9c75-c531558cc53e.png)

**Comment by pooja-pragda** [comment]
![image](https://user-images.githubusercontent.com/76870773/118086190-2f72d380-b3e1-11eb-9f88-a44aa08a5ebb.png)

**Comment by mistry-jignesh** [comment]
Now it is look proper. 

So I have closed the issue.
