### ISSUE TITLE
If pagination option is enable . Paignation option is not visible

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#70]
Like Event Listing and other elements.

![image](https://user-images.githubusercontent.com/75515088/186384531-bdaa3afa-43a6-45f0-ac90-fe9815fd6c2b.png)

![image](https://user-images.githubusercontent.com/75515088/186384705-88402beb-051e-4610-90f8-bbc54eab64ce.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is covered in https://github.com/wpeventmanager/wpem-divi-elements/issues/78

**Comment by mistry-jignesh** [comment]
I have verified this issue. The pagination option is working fine.
The pagination option is visible on the page.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/83d1c0e5-0227-4a26-aa34-2425bb10c7f7)

So I closed the issue.
