### ISSUE TITLE
Frontend/backend - Divi theme - Single event /Single Organizer - Blank page is display 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#72]
When I used  Single event /Single Organizer - option then in the view page is display blank.

On the screen there is not message is display. It should be display message like there is not event.

![image](https://user-images.githubusercontent.com/75515088/186386863-c25e33f8-5ff8-4f7c-9898-eabec77031d8.png)

![image](https://user-images.githubusercontent.com/75515088/186387095-1225d0f6-d255-4004-a949-f6fabfeeef60.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is covered in https://github.com/wpeventmanager/wpem-divi-elements/issues/85

**Comment by mistry-jignesh** [comment]
This issue is similar to the #85 issue. So I will close the issue once fixed issue #85.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.

Single event /Single Organizer default setting is working fine.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/f284f8bd-d5ef-4c48-ad47-6189e06a842e)


![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/6f43b16d-8e91-4416-8e47-21ef26c868d3)
