### ISSUE TITLE
Order by name attribute is not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#73]
Like Event listing and other option.

Order by name attribute is not working .

![image](https://user-images.githubusercontent.com/75515088/186388972-95830894-c724-4c04-8f26-d1ec260bcd82.png)

![image](https://user-images.githubusercontent.com/75515088/186389325-7a052b1f-e944-4541-aa7f-53ba3d793ad1.png)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is working fine. Below is the screenshot.

![Firefox_Screenshot_2023-11-07T06-09-36 886Z](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/d16bb72b-a2d3-47a7-8fcd-008735a7f144)

**Comment by mistry-jignesh** [comment]
I have checked this again but facing the same issue.
Order by name is not working.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/f46d0f8e-b2ba-4d34-82c6-8538b5fbe47a)

**Comment by live-aamir** [comment]
@mistry-jignesh This issue is related with core. The shortcode for events arguments has issue with orderby name.

**Comment by mistry-jignesh** [comment]
As per @live-aamir :  This issue is related to a core. The shortcode for events arguments has an issue with orderby name.
After resolving the issue in the core plugin. This issue will be fixed.
So I have opened the core plugin.

**Comment by RavindraSingh2001** [comment]
@mistry-jignesh As I can see order by title is there to sort theme alphabetically. So order by name doesn't make any sense here as title and name both are same thing and if you check orderby title attribute option then you can see everything is sorted correctly. So I have removed the order by name attribute option.

**Comment by mistry-jignesh** [comment]
As per @RavindraSingh2001 -As I can see order by title is there to sort theme alphabetically. So order by name doesn't make any sense here as title and name both are same thing and if you check orderby title attribute option then you can see everything is sorted correctly. So I have removed the order by name attribute option.
