### ISSUE TITLE
Event Dashboard - Display error message on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#74]
Display error message on the page .

![image](https://user-images.githubusercontent.com/75515088/186395940-3ec60377-e9d9-420d-a7ee-2fba0e36a293.png)

**Comment by live-aamir** [comment]
@mistry-jignesh @krinaydhanani This issue is related to react. It throws error in backend when we use $vb_support = 'on'; in php file

**Comment by mistry-jignesh** [comment]
Now this error message issue is fixed. So I closed the issue.
