### ISSUE TITLE
Text link is not proper overall in all elements

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#75]
![image](https://user-images.githubusercontent.com/121149500/218926996-754446cb-852c-4376-8764-71283b8f15e7.png)

Event Dashboard and WPEM Team link is not proper

Also need to make Wpem text capital like WPEM

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now Text issue is fixed.

In the URL 2 times **https** text is available.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/d8429071-aaa0-4afb-97ab-f92fa5c375d0)

1. Event Listing
2. Event Venue  
3. Event Organizer
4. Single Event Summary

**Comment by mistry-jignesh** [comment]
I have verified URL issue. This issue is fixed.
Now **https** only show one time in the URL.
So I closed the issue.
