### ISSUE TITLE
Event listing drop down fields not display properly

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#77]
![image](https://user-images.githubusercontent.com/121149500/218929258-3a7d444d-ce29-4963-ba63-e0660f598e0c.png)

In divi element if use event listing on page then on front side listing filter event category and type dropdown is not displaying properly

**Comment by live-aamir** [comment]
@mistry-jignesh Both category and event types are working fine. Below are the screenshots.
![Screenshot 2023-11-06 115346](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/82666ac5-685b-46e8-abd0-afd45cb2fc38)
![Screenshot 2023-11-06 115210](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/15ce6de1-3240-4d6c-a1c1-47c82da70496)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now event listing page dropdown field is displayed properly.
It is working fine.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/a021f4ed-0c14-45c8-9b77-3a10ea2a4fd5)
So I closed the issue.
