### ISSUE TITLE
Organizer dashboard element text section content is not proper and not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#82]
![image](https://user-images.githubusercontent.com/121149500/218933428-9f6b81ed-9372-4318-a289-a79403aafe5b.png)

In Organizer dashboard the field in text section is not proper and also it is not working 'Events per page"

**Comment by mistry-jignesh** [comment]
The organizer per page issue is fixed.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/405eed53-eafa-4ff2-9606-c29fd4741eec)  


**Text issue is available. Need to check it.**

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/01d24554-b66a-4b3a-bc60-d684e9270a35)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now the text issue is fixed.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/4d39b3fe-4366-4353-86fa-ee63ed5b7bd8)

So I closed the issue.
