### ISSUE TITLE
Single Event default event is not displaying

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#83]
![image](https://user-images.githubusercontent.com/121149500/218935297-8835339a-e24e-479e-acdb-4babfde65a19.png)
![image](https://user-images.githubusercontent.com/121149500/218935317-c90b0188-6050-431a-a1e0-38d09893fe34.png)
![image](https://user-images.githubusercontent.com/121149500/218935531-7e038dc4-099e-4b97-a992-6f2060e969ae.png)

Single event default event is not displaying.
If we change another event and again select the default selected event then it will display

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now, the default event is displayed using single event option.
This issue is working fine. So I closed the issue.
