### ISSUE TITLE
Single Event Summary default event is not displaying

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#84]
![image](https://user-images.githubusercontent.com/121149500/218935693-bb417aa8-9d51-45a7-bceb-4b5f969eb8bb.png)
![image](https://user-images.githubusercontent.com/121149500/218935705-110faadf-6191-4364-a145-36cdf53deb1a.png)
![image](https://user-images.githubusercontent.com/121149500/218935752-c8e38f7b-e4f1-4215-b204-944b05f19f9b.png)

Single event summary default event is not displaying.
If we change another event and again select the default selected event then it will display

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is fixed.
Single event summary default event is displayed.
It is working fine. So I closed the issue.
