### ISSUE TITLE
Single organizer and venue default selected is not working 

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#85]
![image](https://user-images.githubusercontent.com/121149500/218936194-84f33e3e-b3b6-4fe0-8412-1be2f9757957.png)

**Comment by mistry-jignesh** [comment]
I have verified this issue. Still facing issue with Single venue default setting.
Need to check it.

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.

Single venue default setting is working fine.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/1c06bc4e-d397-4492-a3a5-d444e9ea1db1)

So I closed the issue.
