### ISSUE TITLE
Upcoming event listing some filters are not working

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#86]
![image](https://user-images.githubusercontent.com/121149500/218937583-a7e8aae7-ca7b-48be-b358-dd47f74413e4.png)

In Upcoming event listing locations, category and type vise the filter is not working

**Comment by mistry-jignesh** [comment]
I have verified this issue. Issue facing with category.
Below the image selected 2 categories but only one event is displayed.
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/3cfbe599-f956-44fd-af13-c5af09f8e96e)


Also Here multi-select is possible?

**Comment by mistry-jignesh** [comment]
I have verified this issue.Now filter issue is working .
So I closed the issue.
