### ISSUE TITLE
Venue Dashboard element title should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wpem-divi-elements#87]
![image](https://user-images.githubusercontent.com/121149500/218938314-c6df901b-83f1-4134-a92b-daa72b7abfb3.png)

Current text :- Posts per page
Right text :- Venue Per Page

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
The title name is updated. So I closed the issue.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/7185bdfe-b820-4b55-8aae-63139c6ec7ef)
