### ISSUE TITLE
Need to add description for the Divi elements same as other the adoon

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#88]
Need to add description for the Divi elements same as other the adoon.

![image](https://user-images.githubusercontent.com/75515088/220261414-f41068f8-b43e-48c2-ac80-26541ee851fb.png)

**Comment by Prachetshi1991** [comment]
The Divi Elements addon lets users design their events page with their desired elements at their desired places. It perfectly pairs up with the Divi theme builder to offer a familiar toolset.
https://docs.google.com/document/d/1qRrtKVn0f146hGq2dtYMrGP7Euf0BeVYLey7-k4CDAA/edit
done

**Comment by mistry-jignesh** [comment]
This issue is fixed on the site. Content is added.
So I closed the issue.
