### ISSUE TITLE
Need to fix - Post an event form is not display proper

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#9]
Post an event form is not display proper . 

![image](https://user-images.githubusercontent.com/75515088/117258216-5a51aa80-ae6a-11eb-8d5b-dbdb88c22346.png)

**Comment by pooja-pragda** [comment]
![image](https://user-images.githubusercontent.com/76870773/118082679-3991d380-b3db-11eb-990b-2bf6b42986c6.png)

**Comment by mistry-jignesh** [comment]
This issue is unable to reproduced . 

So Now I have closed the issue.
