### ISSUE TITLE
Event listing page setting screenshot is not relavant

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#92]
URL: https://wp-eventmanager.com/knowledge-base/divi-elements/

Title Name: How to Insert an Event Listing Page.

Here need to correct the image. The title name should be like  **_Event Listing_**

**Need to updated Screenshot :** 

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/a839d0b3-18ec-4718-92f5-5968bda3ec74)

**Comment by Prachetshi1991** [comment]
This issue is related to images only

**Comment by mistry-jignesh** [comment]
I have verified this issue. Now this issue is fixed.
A screenshot is updated and it is proper.
So I closed the issue.
