### ISSUE TITLE
Issue with wordpress 6.4 : Click on then enable visual builder option then option is not loading

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#93]
Click on then enable visual builder option then option is not loading.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/caad6997-1d25-4c6f-9d2a-797132ee9edd)

**Comment by live-aamir** [comment]
@mistry-jignesh it is working fine in version 6.4 . Below is the screenshot
![image (2)](https://github.com/wpeventmanager/wpem-divi-elements/assets/49248762/b28125f4-fc29-42c4-b88e-cdaec8359622)

**Comment by mistry-jignesh** [comment]
I have checked this issue in the new setup.
This issue is working fine. The file is downloaded properly.
So I closed the issue.
