### ISSUE TITLE
Single Event Summary attribute width and featured not working 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#94]
Single Event Summary attribute width and feature not working.

1. Changed Width values but there is no reflection in the preview.
2. Feature as select false then also event is displayed.

![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/75515088/9e2e480e-8b40-4393-b986-2766de64a765)

**Comment by live-aamir** [comment]
@mistry-jignesh I have tested it with latest version of core and our divi-elements add on, it is working fine.
Please check.

**Comment by mistry-jignesh** [comment]
This issue is working properly. So I closed the issue.
