### ISSUE TITLE
PHP 8.2  Deprecated code error

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#96]
Deprecated: Creation of dynamic property WP_Event_Manager_Alerts::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-alerts/wp-event-manager-alerts.php on line 88

Deprecated: Creation of dynamic property WPEM_Registrations::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-registrations/wp-event-manager-registrations.php on line 96

Deprecated: Creation of dynamic property WP_Event_Manager_Settings::$settings_group is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-settings.php on line 21

Deprecated: Creation of dynamic property WP_Event_Manager_Admin::$settings_page is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-admin.php on line 29

Deprecated: Creation of dynamic property WP_Event_Manager::$forms is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/wp-event-manager.php on line 104

Deprecated: Creation of dynamic property WP_Event_Manager::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/wp-event-manager.php on line 105

**Comment by mistry-jignesh** [comment]
I have verified issue. Deprecated code error is fixed.
So I closed the issue.

**Comment by ritakikani** [comment]
![image](https://github.com/wpeventmanager/wpem-divi-elements/assets/25837982/fa6905c4-c379-4cd3-8aa9-a38365e726ef)

**Comment by RavindraSingh2001** [comment]
@ritakikani Mam, WPEM_WpEventManagerDiviElements class extends DiviExtension class and those 2 properties $plugin_dir and $plugin_dir_url are declared in the DiviExtension class so we can use both properties without declaring in the child class and it is valid and doesn't create any deprecated code errors that's why I didn't declared those properties here in the child class.

Let me know your thoughts on this please.

**Comment by ritakikani** [comment]
@RavindraSingh2001 , then it is ok, there is no issue.

**Comment by ritakikani** [comment]
@mistry-jignesh Code review is done from my side, so please test it and close if issue resolve.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now Deprecated code error is fixed.
So I closed the issue.

**Comment by mistry-jignesh** [comment]
I have verified the issue. Now, the Deprecated code error is fixed.
So I closed the issue.
